### ISSUE TITLE
handling of attributes in cmk_host_registration

### ISSUE THREAD

**Issue by FloMiau** [tribe29/ansible-checkmk#11]
Hey there,

I'm setting attributes for my hosts.

This is my task for that:
```yaml
- name: Add host
  local_action:
    module: checkmk_host
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    name: "{{ cmk_client_name }}"
    folder: "{{ cmk_site_default_folder }}"
    state: present
    discover_services: false
    activate_changes: false
    attributes:
      tag_address_family: 'ip-v4v6'
```

Expected behaviour:
the attribute is set. If the attribute is already set do nothing.

Actual behaviour:
the module is unsetting attributes which aren't in my dict. It does another API call to update my host.

This wouldn't be a problem if I would know all of my attributes inside my playbook. I know that I'm using a dual stack setup nothing else.

Right now I've commented out the [code for deleting attributes](https://github.com/tribe29/ansible-checkmk/blob/master/roles/cmk_host_registration/library/checkmk_host.py#L148-L150).

I would suggest two variants:
1)  a boolean parameter called "remove_attributes"
2) a list parameter which explicitly removes attributes

Thanks.
Florian
