### ISSUE TITLE
"The site is currently locked by another activation process."

### ISSUE THREAD

**Issue by FloMiau** [tribe29/ansible-checkmk#9]
Hey there,

I'm experimenting with adding a lot of hosts to my site. I'm using checkmk raw 1.6.0p19.

At first I had the parameter activate_changes on. That means every add of a host created an activate. Since I've run that in parallel there were a lot of concurring activations.

This resulted in some side effects. It is only one activation at the same time allowed. So I got the message "The site is currently locked by another activation process. Please try again later".

Expected output: the task should fail.

Please see the output of the task below.

Thanks

example task:
```yaml

- name: Add host
  local_action:
    module: checkmk_host
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    name: "{{ cmk_client_name }}"
    folder: "{{ cmk_site_default_folder }}"
    state: present
    #discover_services: false
    #activate_changes: false
    attributes:
      tag_address_family: 'ip-v4v6'
```

Log:
```
TASK [add host] ************************
ok: [netbox.example.com] => {
    "msg": {
        "activate_changes": {
            "result": {
                "sites": {
                    "example": {
                        "_expected_duration": 4.199194787758159,
                        "_phase": "done",
                        "_pid": null,
                        "_site_id": "example",
                        "_state": "warning",
                        "_status_details": "Started at: 18:14:40. Finished at: 18:14:40.<br>The site is currently locked by another activation process. Please try again later",
                        "_status_text": "Locked",
                        "_time_ended": 1609866880.763883,
                        "_time_started": null,
                        "_time_updated": 1609866880.763883,
                        "_warnings": []
                    }
                }
            },
            "status": 0
        },
        "changed": true,
        "failed": false,
        "hostname": "netbox.example.com",
        "request": {
            "attributes": {
                "tag_address_family": "ip-v4v6"
            },
            "folder": "",
            "hostname": "netbox.example.com"
        },
        "result": null,
        "service_discovery": {
            "result": "Service discovery successful. Added 16, removed 16, kept 0, total 16 services and 0 new, 0 total host labels",
            "status": 0
        }
    }
}
```
